import { type NextPage } from "next";
import Head from "next/head";
import type { FormEventHandler} from "react";
import { useRef } from "react";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { data } = trpc.example.links.useQuery()
  const utils = trpc.useContext()
  const inputRef = useRef<HTMLInputElement>(null)
  const addLink = trpc.example.addLink.useMutation({onSuccess() {
    if (inputRef.current?.value) {
      inputRef.current.value = ''
    }
    utils.example.links.invalidate()
  }})
  
  const onAddLink:FormEventHandler<HTMLFormElement> = (e) => {
    e.preventDefault()
    if (!inputRef.current?.value) return
    addLink.mutate({ url: inputRef.current.value })
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col gap-4 p-4">
        <form onSubmit={onAddLink}>
        <div className="flex">
          <input disabled={addLink.isLoading} ref={inputRef} className="p-2 border-2" placeholder="https://google.com..." />
          <button type="submit" className="bg-blue-200 p-2">add</button>
        </div>
        </form>
        <hr />
        <div className="">
          {data?.map(link => (
            <div  key={link.url}>
              <a target="_blank" href={link.url} rel="noreferrer">{link.url}</a>
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
