import { type NextPage } from 'next'
import Head from 'next/head'
import { FormEventHandler, useState } from 'react'
import { useRef } from 'react'

import { trpc } from '../utils/trpc'

const cs = (obj: Array<string>): string => obj.join(' ')

const Home: NextPage = () => {
  const [search, setSearch] = useState('')
  const { data } = trpc.example.links.useQuery()
  const utils = trpc.useContext()
  const inputRef = useRef<HTMLInputElement>(null)
  const addLink = trpc.example.addLink.useMutation({
    onSuccess() {
      if (inputRef.current?.value) {
        inputRef.current.value = ''
      }
      utils.example.links.invalidate()
    },
    onError(err) {
      console.log(err)
    },
  })

  const onAddLink: FormEventHandler<HTMLFormElement> = (e) => {
    e.preventDefault()
    if (!inputRef.current?.value) {
      setSearch('')

      return
    }

    const { value } = inputRef.current
    if (value.includes('http')) {
      addLink.mutate({ url: value })
    } else {
      setSearch(value)
    }
  }

  const filteredLinks =
    data?.filter(
      (link) => !search || link.url.includes(search) || link.desc?.toLowerCase().includes(search)
    ) || []

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <meta name="theme-color" content="rgb(203, 213, 225)" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col gap-4 bg-slate-300 p-4">
        <form onSubmit={onAddLink}>
          <div className="flex">
            <input
              disabled={addLink.isLoading}
              ref={inputRef}
              className="w-full rounded-lg p-2 focus:shadow-md"
              placeholder="http..."
            />
            <button type="submit" className="hidden bg-blue-300 p-2">
              add
            </button>
          </div>
        </form>
        <div className="flex flex-1 flex-wrap gap-4 overflow-auto">
          {filteredLinks.map((link) => (
            <a
              key={link.url}
              className={cs([
                'bg-slate-200',
                'flex-col',
                'flex',
                'group',
                'items-center',
                'md:max-w-sm',
                'p-2',
                'rounded-lg',
                'shadow-lg',
                'w-full',
                'hover:bg-slate-50',
                'transition-colors',
                'duration-300',
              ])}
              target="_blank"
              href={link.url}
              rel="noreferrer"
            >
              <img alt="image" className={cs(['h-36', 'rounded-lg'])} src={link.image} />
              <div className="font-semibold text-slate-700 line-clamp-2">{link.desc}</div>
              <div className="flex-1"></div>
              <div className="font-mono text-xs text-gray-400">{link.url}</div>
            </a>
          ))}
        </div>
      </main>
    </>
  )
}

export default Home
